#:kivy 1.10.0

<ScreenManagement>:
    MainScreen:
        id: main
    HomePage:

<MainScreen>:
    name: "main_screen"
    GridLayout:
        size_hint: (0.5, 0.5)
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        cols: 2
        padding: 20

        Label:
            size_hint: (0.2, 0.2)
            text: "User Name"
            font_size: 30
            text_size: self.size
            valign: "middle"

        TextInput:
            id: username
            size_hint: (0.2, 0.06)
            cursor_blink: True
            font_size: 20
            multiline: False

        Label:
            size_hint: (0.2, 0.2)
            text:"Pin:"
            font_size: 30
            text_size: self.size
            valign: "middle"

        TextInput:
            id: pin
            size_hint: (0.2, 0.06)
            cursor_blink: True
            font_size: 20
            multiline: False
            password: True

        Button:
            size_hint_y: None
            height: 90
            text: 'Logged users'

        Button:
            size_hint_y: None
            height: 90
            text:'Create user'
            on_press: root.manager.ids.main.login(username.text, pin.text)

<HomePage>:
    name: "homepage"
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Home Page"
        Button:
            text: "Go to main screen"
            size_hint_y: 0.1
            on_press: root.manager.current = "main_screen"